# Tech Workforce Intelligence Analytics: Hiring, Layoffs, AI Adoption & Employee Sentiment Analysis

* This project focuses on analyzing workforce trends in the global technology industry using data related to hiring patterns, layoffs, AI adoption, employee sentiment, and market conditions.

* The objective is to identify workforce trends, understand factors influencing organizational decisions, and generate actionable business insights. Using SQL for business queries, Python for exploratory and advanced analysis, and Power BI for interactive dashboards, the project aims to uncover meaningful patterns and support data-driven decision-making through workforce intelligence analysis.

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
engine = create_engine(
    "mysql+mysqlconnector://root:123456@localhost:3306/tech_layoffs_hiring_trends"
)

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    tables = [row[0] for row in result]

print("Total Tables:", len(tables))
print("Table Names:")
for table in tables:
    print("-", table)

Total Tables: 1
Table Names:
- tech_layoffs_hiring_trends

In [3]:
tables = ["tech_layoffs_hiring_trends"]
for table in tables:
       print(f"\n Table: {table}")
       query = text(f"SELECT COUNT(*) FROM {table}")
       df = pd.read_sql_query(query, engine)
       print(f"{table}", df.iloc[0,0])
       display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5", engine))

 Table: tech_layoffs_hiring_trends
tech_layoffs_hiring_trends 12000

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market

In [14]:
df = pd.read_sql_query(text("""select * from tech_layoffs_hiring_trends"""),engine)
df

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,...,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,...,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,...,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,...,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,...,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market

In [11]:
print(f"data info : {df.info()}")
print("-"* 40)
print(f" null check : \n{df.isnull().sum()}")
print("-"* 40)
print(f"duplicate data : {df.duplicated().sum()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   record_id               12000 non-null  object
 1   company_name            12000 non-null  object
 2   industry                12000 non-null  object
 3   country                 12000 non-null  object
 4   company_size            12000 non-null  object
 5   month                   12000 non-null  object
 6   year                    12000 non-null  int64
 7   layoffs_count           12000 non-null  int64
 8   layoff_percentage       12000 non-null  float64
 9   reason_for_layoffs      12000 non-null  object
 10  ai_automation_impact    12000 non-null  float64
 11  ai_replacement_risk     12000 non-null  float64
 12  open_roles              12000 non-null  int64
 13  hiring_trend            12000 non-null  object
 14  remote_jobs_percentage  12000 non-null  float64
 15  top_hiring_role         12000 non-null  object
 16  stock_growth_percent    12000 non-null  float64
 17  revenue_growth_percent  12000 non-null  float64
 18  salary_budget_change    12000 non-null  float64
 19  ai_adoption_level       12000 non-null  float64
 20  employee_sentiment      12000 non-null  float64
 21  job_security_score      12000 non-null  float64
 22  market_condition        12000 non-null  object
dtypes: float64(10), int64(3), object(10)
memory usage: 2.1+ MB
data info : None
----------------------------------------
 null check :
record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64
----------------------------------------
duplicate data : 0

In [12]:
# remove whitespace from object columns
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.strip()

In [16]:
df = df.drop(columns=['record_id'])

In [17]:
df

,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,ai_automation_impact,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,6.4,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,0.9,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,7.1,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,10.4,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,11.4,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,5.6,...,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market
11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,3.4,...,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable
11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,8.3,...,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession
11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,9.1,...,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market
11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,2.4,...,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market

In [18]:
df.to_sql(name="clean_dataset",
          con=engine , 
          if_exists="replace" , 
          index=False,
          chunksize=500)
print("clean dataset save in mysql")

clean dataset save in mysql

In [19]:
df_verify = pd.read_sql("SELECT * FROM clean_dataset LIMIT 5", engine)
display(df_verify)

,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,ai_automation_impact,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,6.4,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,0.9,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,7.1,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,10.4,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,11.4,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market

In [20]:
original_count = pd.read_sql("SELECT COUNT(*) AS cnt FROM clean_dataset", engine)
print(f"✓ Rows in MySQL  : {original_count['cnt'][0]}")
print(f"✓ Rows in df     : {len(df)}")
print(f"✓ Match          : {original_count['cnt'][0] == len(df)}")

✓ Rows in MySQL  : 12000
✓ Rows in df     : 12000
✓ Match          : True