# sql analysis

In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
engine = create_engine(
    "mysql+mysqlconnector://root:123456@localhost:3306/sentiment_analysis"
)

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    tables = [row[0] for row in result]

print("Total Tables:", len(tables))
print("Table Names:")
for table in tables:
    print("-", table)

Total Tables: 1
Table Names:
- sentiment_dataset

In [3]:
tables = ["sentiment_dataset"]
for table in tables:
       print(f"\n Table: {table}")
       query = text(f"SELECT COUNT(*) FROM {table}")
       df = pd.read_sql_query(query, engine)
       print(f"{table}", df.iloc[0,0])
       display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5", engine))

 Table: sentiment_dataset
sentiment_dataset 732

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [4]:
with engine.begin() as conn:
    conn.execute(
        text("""
            ALTER TABLE sentiment_dataset
            DROP COLUMN `Unnamed: 0.1`,
            DROP COLUMN `Unnamed: 0`
        """)
    )

print("Unnamed column dropped")

Unnamed column dropped

In [5]:
with engine.begin() as conn:
    result = conn.execute(text("DESCRIBE sentiment_dataset"))
    for row in result:
        print(row)

('Text', 'varchar(255)', 'YES', '', None, '')
('Sentiment', 'varchar(255)', 'YES', '', None, '')
('Timestamp', 'varchar(255)', 'YES', '', None, '')
('User', 'varchar(255)', 'YES', '', None, '')
('Platform', 'varchar(255)', 'YES', '', None, '')
('Hashtags', 'varchar(255)', 'YES', '', None, '')
('Retweets', 'float', 'YES', '', None, '')
('Likes', 'float', 'YES', '', None, '')
('Country', 'varchar(255)', 'YES', '', None, '')
('Year', 'int', 'YES', '', None, '')
('Month', 'int', 'YES', '', None, '')
('Day', 'int', 'YES', '', None, '')
('Hour', 'int', 'YES', '', None, '')

In [7]:
with engine.begin() as conn:
    conn.execute(
        text("""
            ALTER TABLE sentiment_dataset
            DROP COLUMN Text,
            DROP COLUMN Hashtags
        """)
    )

print("column dropped")

column dropped

In [8]:
df = pd.read_sql(
    "SELECT * FROM sentiment_dataset",
    engine
)

display(df)

,Sentiment,Timestamp,User,Platform,Retweets,Likes,Country,Year,Month,Day,Hour
0,Positive,2023-01-15 12:30:00,User123,Twitter,15.0,30.0,USA,2023,1,15,12
1,Negative,2023-01-15 08:45:00,CommuterX,Twitter,5.0,10.0,Canada,2023,1,15,8
2,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,20.0,40.0,USA,2023,1,15,15
3,Positive,2023-01-15 18:20:00,AdventureX,Facebook,8.0,15.0,UK,2023,1,15,18
4,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,20.0,39.0,UK,2017,8,18,18
728,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,25.0,48.0,USA,2018,6,22,14
729,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,22.0,42.0,Canada,2019,4,5,17
730,Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,21.0,43.0,UK,2020,2,29,20
731,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,24.0,47.0,USA,2020,11,15,15

In [9]:
# remove white spaces from all 
for i in df.select_dtypes(include=["object"]).columns:
    df[i] = df[i].astype(str).str.strip()

df

,Sentiment,Timestamp,User,Platform,Retweets,Likes,Country,Year,Month,Day,Hour
0,Positive,2023-01-15 12:30:00,User123,Twitter,15.0,30.0,USA,2023,1,15,12
1,Negative,2023-01-15 08:45:00,CommuterX,Twitter,5.0,10.0,Canada,2023,1,15,8
2,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,20.0,40.0,USA,2023,1,15,15
3,Positive,2023-01-15 18:20:00,AdventureX,Facebook,8.0,15.0,UK,2023,1,15,18
4,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,12.0,25.0,Australia,2023,1,15,19
...,...,...,...,...,...,...,...,...,...,...,...
727,Happy,2017-08-18 18:20:00,ScienceProjectSuccessHighSchool,Facebook,20.0,39.0,UK,2017,8,18,18
728,Happy,2018-06-22 14:15:00,BirthdayPartyJoyHighSchool,Instagram,25.0,48.0,USA,2018,6,22,14
729,Happy,2019-04-05 17:30:00,CharityFundraisingTriumphHighSchool,Twitter,22.0,42.0,Canada,2019,4,5,17
730,Happy,2020-02-29 20:45:00,MulticulturalFestivalJoyHighSchool,Facebook,21.0,43.0,UK,2020,2,29,20
731,Happy,2020-11-15 15:15:00,VirtualTalentShowSuccessHighSchool,Instagram,24.0,47.0,USA,2020,11,15,15

In [10]:
print(f"data types:\n{df.dtypes}")
print("-"*30)
print(f"missing values:\n{df.isnull().sum()}")
print("-"*30)
print(f"duplicate values:\n{df.duplicated().sum()}")
print("-"*30)
print(f' info :\n{df.info()}')
print("-"*30)
print(f"data shape : {df.shape}")

data types:
Sentiment     object
Timestamp     object
User          object
Platform      object
Retweets     float64
Likes        float64
Country       object
Year           int64
Month          int64
Day            int64
Hour           int64
dtype: object
------------------------------
missing values:
Sentiment    0
Timestamp    0
User         0
Platform     0
Retweets     0
Likes        0
Country      0
Year         0
Month        0
Day          0
Hour         0
dtype: int64
------------------------------
duplicate values:
28
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sentiment  732 non-null    object
 1   Timestamp  732 non-null    object
 2   User       732 non-null    object
 3   Platform   732 non-null    object
 4   Retweets   732 non-null    float64
 5   Likes      732 non-null    float64
 6   Country    732 non-null    object
 7   Year       732 non-null    int64
 8   Month      732 non-null    int64
 9   Day        732 non-null    int64
 10  Hour       732 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 63.0+ KB
 info :
None
------------------------------
data shape : (732, 11)

In [11]:
df = df.drop_duplicates()

In [12]:
print(f"after removing duplicates, data shape : {df.shape}")

after removing duplicates, data shape : (704, 11)

In [13]:
# unique values in sentiment column
for col in df.select_dtypes(include='object').columns:
    print(df[col].value_counts())

Sentiment
Positive                45
Joy                     44
Excitement              37
Contentment             18
Neutral                 18
                        ..
Celestial Wonder         1
Nature's Beauty          1
Thrilling Journey        1
Whispers of the Past     1
Relief                   1
Name: count, Length: 191, dtype: int64
Timestamp
2019-04-05 17:30:00    3
2020-04-12 19:30:00    2
2022-07-17 06:15:00    2
2021-07-01 12:10:00    2
2022-01-07 11:10:00    2
                      ..
2016-09-14 12:30:00    1
2017-08-18 18:20:00    1
2018-06-22 14:15:00    1
2020-02-29 20:45:00    1
2023-01-18 10:30:00    1
Name: count, Length: 683, dtype: int64
User
NatureAdmirer                          3
Bookworm                               3
DawnGardener                           2
ForestDreamer                          2
GardenEnthusiast                       2
                                      ..
ScienceProjectSuccessHighSchool        1
BirthdayPartyJoyHighSchool             1
CharityFundraisingTriumphHighSchool    1
MulticulturalFestivalJoyHighSchool     1
CommuterX                              1
Name: count, Length: 670, dtype: int64
Platform
Instagram    247
Twitter      236
Facebook     221
Name: count, dtype: int64
Country
USA               184
UK                140
Canada            131
Australia          70
India              68
France             16
Brazil             16
Japan              15
Germany            14
Italy              11
Greece              5
Spain               5
South Africa        5
Netherlands         3
Switzerland         2
Belgium             2
Sweden              1
Portugal            1
Austria             1
Denmark             1
Czech Republic      1
Jordan              1
Peru                1
Maldives            1
China               1
Cambodia            1
Norway              1
Colombia            1
Ireland             1
Jamaica             1
Kenya               1
Scotland            1
Thailand            1
Name: count, dtype: int64

In [14]:
df.to_csv("clean_dataset.csv" , index=False)
print("cleaned dataset saved")

cleaned dataset saved

In [15]:
df.to_sql(
    "clean_dataset",
    con=engine,
    if_exists='replace',
    index=False
)

print("Data saved into MySQL")

Data saved into MySQL