In [1]:
from sqlalchemy import create_engine, text
import sqlalchemy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

In [2]:
engine = create_engine(
    f"mysql+mysqlconnector://{os.environ['DB_USER']}:{os.environ['DB_PASSWORD']}@{os.environ['DB_HOST']}/{os.environ['DB_NAME']}"
)

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    tables = [row[0] for row in result]

print("Total Tables:", len(tables))
print("Table Names:")
for table in tables:
    print("-", table)

Total Tables: 8
Table Names:
- order_details
- order_details_clean
- orders
- orders_clean
- pizza_types
- pizza_types_clean
- pizzas
- pizzas_clean

In [5]:
orders = pd.read_sql_query("SELECT * FROM orders_clean", engine)
order_details = pd.read_sql_query("SELECT * FROM  order_details_clean", engine)
pizzas = pd.read_sql_query("SELECT * FROM pizzas_clean", engine)
pizza_types = pd.read_sql_query("SELECT * FROM pizza_types_clean", engine)

print("clean dataset loaded Successfully\n")

display("Orders:", orders.head())
display("Order Details:", order_details.head())
display("Pizzas:", pizzas.head())
display("Pizza Types:", pizza_types.head())

clean dataset loaded Successfully

'Orders:'

   order_id order_date order_time
0         1   1/1/2015   11:38:36
1         2   1/1/2015   11:57:40
2         3   1/1/2015   12:12:28
3         4   1/1/2015   12:16:31
4         5   1/1/2015   12:21:30

'Order Details:'

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1
2                 3         2  five_cheese_l         1
3                 4         2    ital_supr_l         1
4                 5         2     mexicana_m         1

'Pizzas:'

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

'Pizza Types:'

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."

* SQL Analysis

In [6]:
orders

       order_id  order_date order_time
0             1    1/1/2015   11:38:36
1             2    1/1/2015   11:57:40
2             3    1/1/2015   12:12:28
3             4    1/1/2015   12:16:31
4             5    1/1/2015   12:21:30
...         ...         ...        ...
21345     21346  12/31/2015   20:51:07
21346     21347  12/31/2015   21:14:37
21347     21348  12/31/2015   21:23:10
21348     21349  12/31/2015   22:09:54
21349     21350  12/31/2015   23:02:05

[21350 rows x 3 columns]