# data clean

In [1]:
from sqlalchemy import create_engine, text
import sqlalchemy
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

In [2]:
engine = create_engine(
    f"mysql+mysqlconnector://{os.environ['DB_USER']}:{os.environ['DB_PASSWORD']}@{os.environ['DB_HOST']}/{os.environ['DB_NAME']}"
)

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    tables = [row[0] for row in result]

print("Total Tables:", len(tables))
print("Table Names:")
for table in tables:
    print("-", table)

Total Tables: 1
Table Names:
- myntra_sales_dataset

In [3]:
for table in tables:
       print(f"\n Table: {table}")
    #    query = text(f"SELECT COUNT(*) FROM {table}")
       df = pd.read_sql_query(text(f"SELECT COUNT(*) FROM {table}"), engine)
       print(f"{table}", df.iloc[0,0])
       df = pd.read_sql(f"SELECT * FROM {table}", engine)
       display(df)

 Table: myntra_sales_dataset
myntra_sales_dataset 8000

,Order_ID,Order_Date,Order_Month,Order_Quarter,Order_Year,Customer_ID,Customer_Name,Gender,Age,City,...,MRP,Discount_Percent,Selling_Price,Quantity,Total_Amount,Payment_Mode,Order_Channel,Order_Status,Delivery_Days,Rating
0,MYN100001,2023-03-03,March,Q1,2023,CUST00139,Vaishnavi Sathe,Female,27,Delhi,...,5729.0,50,2864.5,1,2864.5,UPI,Website,Delivered,3,5.0
1,MYN100002,2024-03-13,March,Q1,2024,CUST00298,Geetika Mistry,Female,40,Guwahati,...,2129.0,0,2129.0,1,2129.0,Debit Card,Mobile App,Delivered,9,5.0
2,MYN100003,2025-05-13,May,Q2,2025,CUST01162,Arunima Chokshi,Female,39,Kolkata,...,5699.0,10,5129.1,1,5129.1,Credit Card,Mobile App,Delivered,8,3.0
3,MYN100004,2023-02-13,February,Q1,2023,CUST02043,Hemang Mitter,Male,48,Jaipur,...,2169.0,30,1518.3,1,1518.3,UPI,Mobile App,Cancelled,6,NaN
4,MYN100005,2023-07-14,July,Q3,2023,CUST00020,Peter Kadakia,Male,52,Surat,...,1729.0,0,1729.0,1,1729.0,Cash on Delivery,Website,Delivered,8,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,MYN107996,2025-09-28,September,Q3,2025,CUST01946,Januja Borah,Female,52,Lucknow,...,929.0,20,743.2,2,1486.4,UPI,Mobile App,Delivered,5,4.0
7996,MYN107997,2024-10-19,October,Q4,2024,CUST00377,Chaman Chander,Female,26,Pune,...,1189.0,10,1070.1,2,2140.2,Cash on Delivery,Mobile App,Delivered,2,5.0
7997,MYN107998,2025-01-20,January,Q1,2025,CUST01432,Indrajit Dave,Male,55,Jaipur,...,1019.0,20,815.2,2,1630.4,Cash on Delivery,Mobile Web,Delivered,9,4.0
7998,MYN107999,2025-06-03,June,Q2,2025,CUST01225,Veer Halder,Male,51,Patna,...,1369.0,40,821.4,1,821.4,Debit Card,Website,Returned,4,NaN
7999,MYN108000,2024-12-04,December,Q4,2024,CUST00668,Siddharth Padmanabhan,Male,38,Chandigarh,...,959.0,50,479.5,1,479.5,Debit Card,Mobile Web,Pending,6,NaN

In [4]:
df = df.replace("NaN", np.nan)

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['order_id', 'order_date', 'order_month', 'order_quarter', 'order_year',
       'customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'membership_tier', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'color', 'size', 'mrp', 'discount_percent',
       'selling_price', 'quantity', 'total_amount', 'payment_mode',
       'order_channel', 'order_status', 'delivery_days', 'rating'],
      dtype='object')

In [6]:
df = df.drop(columns = ['customer_name'])

In [7]:
df.info()
print("-"* 40)
print(f"null check : \n{df.isnull().sum()}")
print("-"* 40)
print(f"duplicate data : {df.duplicated().sum()}")
print("-"* 40)
print(f"data shape : {df.shape}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          8000 non-null   object
 1   order_date        8000 non-null   object
 2   order_month       8000 non-null   object
 3   order_quarter     8000 non-null   object
 4   order_year        8000 non-null   int64
 5   customer_id       8000 non-null   object
 6   gender            8000 non-null   object
 7   age               8000 non-null   int64
 8   city              8000 non-null   object
 9   state             8000 non-null   object
 10  membership_tier   8000 non-null   object
 11  product_id        8000 non-null   object
 12  product_name      8000 non-null   object
 13  category          8000 non-null   object
 14  sub_category      8000 non-null   object
 15  brand             8000 non-null   object
 16  color             8000 non-null   object
 17  size              8000 non-null   object
 18  mrp               8000 non-null   float64
 19  discount_percent  8000 non-null   int64
 20  selling_price     8000 non-null   float64
 21  quantity          8000 non-null   int64
 22  total_amount      8000 non-null   float64
 23  payment_mode      8000 non-null   object
 24  order_channel     8000 non-null   object
 25  order_status      8000 non-null   object
 26  delivery_days     8000 non-null   int64
 27  rating            5858 non-null   float64
dtypes: float64(4), int64(5), object(19)
memory usage: 1.7+ MB
----------------------------------------
null check :
order_id               0
order_date             0
order_month            0
order_quarter          0
order_year             0
customer_id            0
gender                 0
age                    0
city                   0
state                  0
membership_tier        0
product_id             0
product_name           0
category               0
sub_category           0
brand                  0
color                  0
size                   0
mrp                    0
discount_percent       0
selling_price          0
quantity               0
total_amount           0
payment_mode           0
order_channel          0
order_status           0
delivery_days          0
rating              2142
dtype: int64
----------------------------------------
duplicate data : 0
----------------------------------------
data shape : (8000, 28)

In [8]:
num_cols = ['rating']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [9]:
print("after handling null values")
print("--"* 20)
print(df.isnull().sum())

after handling null values
----------------------------------------
order_id            0
order_date          0
order_month         0
order_quarter       0
order_year          0
customer_id         0
gender              0
age                 0
city                0
state               0
membership_tier     0
product_id          0
product_name        0
category            0
sub_category        0
brand               0
color               0
size                0
mrp                 0
discount_percent    0
selling_price       0
quantity            0
total_amount        0
payment_mode        0
order_channel       0
order_status        0
delivery_days       0
rating              0
dtype: int64

In [19]:
# check unique values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    vals = df[col].unique()
    print(f"\n{col} ({len(vals)} unique): {sorted(vals)}")

order_id (8000 unique): ['MYN100001', 'MYN100002', 'MYN100003', 'MYN100004', 'MYN100005', 'MYN100006', 'MYN100007', 'MYN100008', 'MYN100009', 'MYN100010', 'MYN100011', 'MYN100012', 'MYN100013', 'MYN100014', 'MYN100015', 'MYN100016', 'MYN100017', 'MYN100018', 'MYN100019', 'MYN100020', 'MYN100021', 'MYN100022', 'MYN100023', 'MYN100024', 'MYN100025', 'MYN100026', 'MYN100027', 'MYN100028', 'MYN100029', 'MYN100030', 'MYN100031', 'MYN100032', 'MYN100033', 'MYN100034', 'MYN100035', 'MYN100036', 'MYN100037', 'MYN100038', 'MYN100039', 'MYN100040', 'MYN100041', 'MYN100042', 'MYN100043', 'MYN100044', 'MYN100045', 'MYN100046', 'MYN100047', 'MYN100048', 'MYN100049', 'MYN100050', 'MYN100051', 'MYN100052', 'MYN100053', 'MYN100054', 'MYN100055', 'MYN100056', 'MYN100057', 'MYN100058', 'MYN100059', 'MYN100060', 'MYN100061', 'MYN100062', 'MYN100063', 'MYN100064', 'MYN100065', 'MYN100066', 'MYN100067', 'MYN100068', 'MYN100069', 'MYN100070', 'MYN100071', 'MYN100072', 'MYN100073', 'MYN100074', 'MYN100075', 'MYN100076', 'MYN100077', 'MYN100078', 'MYN100079', 'MYN100080', 'MYN100081', 'MYN100082', 'MYN100083', 'MYN100084', 'MYN100085', 'MYN100086', 'MYN100087', 'MYN100088', 'MYN100089', 'MYN100090', 'MYN100091', 'MYN100092', 'MYN100093', 'MYN100094', 'MYN100095', 'MYN100096', 'MYN100097', 'MYN100098', 'MYN100099', 'MYN100100', 'MYN100101', 'MYN100102', 'MYN100103', 'MYN100104', 'MYN100105', 'MYN100106', 'MYN100107', 'MYN100108', 'MYN100109', 'MYN100110', 'MYN100111', 'MYN100112', 'MYN100113', 'MYN100114', 'MYN100115', 'MYN100116', 'MYN100117', 'MYN100118', 'MYN100119', 'MYN100120', 'MYN100121', 'MYN100122', 'MYN100123', 'MYN100124', 'MYN100125', 'MYN100126', 'MYN100127', 'MYN100128', 'MYN100129', 'MYN100130', 'MYN100131', 'MYN100132', 'MYN100133', 'MYN100134', 'MYN100135', 'MYN100136', 'MYN100137', 'MYN100138', 'MYN100139', 'MYN100140', 'MYN100141', 'MYN100142', 'MYN100143', 'MYN100144', 'MYN100145', 'MYN100146', 'MYN100147', 'MYN100148', 'MYN100149', 'MYN100150', 'MYN100151', 'MYN100152', 'MYN100153', 'MYN100154', 'MYN100155', 'MYN100156', 'MYN100157', 'MYN100158', 'MYN100159', 'MYN100160', 'MYN100161', 'MYN100162', 'MYN100163', 'MYN100164', 'MYN100165', 'MYN100166', 'MYN100167', 'MYN100168', 'MYN100169', 'MYN100170', 'MYN100171', 'MYN100172', 'MYN100173', 'MYN100174', 'MYN100175', 'MYN100176', 'MYN100177', 'MYN100178', 'MYN100179', 'MYN100180', 'MYN100181', 'MYN100182', 'MYN100183', 'MYN100184', 'MYN100185', 'MYN100186', 'MYN100187', 'MYN100188', 'MYN100189', 'MYN100190', 'MYN100191', 'MYN100192', 'MYN100193', 'MYN100194', 'MYN100195', 'MYN100196', 'MYN100197', 'MYN100198', 'MYN100199', 'MYN100200', 'MYN100201', 'MYN100202', 'MYN100203', 'MYN100204', 'MYN100205', 'MYN100206', 'MYN100207', 'MYN100208', 'MYN100209', 'MYN100210', 'MYN100211', 'MYN100212', 'MYN100213', 'MYN100214', 'MYN100215', 'MYN100216', 'MYN100217', 'MYN100218', 'MYN100219', 'MYN100220', 'MYN100221', 'MYN100222', 'MYN100223', 'MYN100224', 'MYN100225', 'MYN100226', 'MYN100227', 'MYN100228', 'MYN100229', 'MYN100230', 'MYN100231', 'MYN100232', 'MYN100233', 'MYN100234', 'MYN100235', 'MYN100236', 'MYN100237', 'MYN100238', 'MYN100239', 'MYN100240', 'MYN100241', 'MYN100242', 'MYN100243', 'MYN100244', 'MYN100245', 'MYN100246', 'MYN100247', 'MYN100248', 'MYN100249', 'MYN100250', 'MYN100251', 'MYN100252', 'MYN100253', 'MYN100254', 'MYN100255', 'MYN100256', 'MYN100257', 'MYN100258', 'MYN100259', 'MYN100260', 'MYN100261', 'MYN100262', 'MYN100263', 'MYN100264', 'MYN100265', 'MYN100266', 'MYN100267', 'MYN100268', 'MYN100269', 'MYN100270', 'MYN100271', 'MYN100272', 'MYN100273', 'MYN100274', 'MYN100275', 'MYN100276', 'MYN100277', 'MYN100278', 'MYN100279', 'MYN100280', 'MYN100281', 'MYN100282', 'MYN100283', 'MYN100284', 'MYN100285', 'MYN100286', 'MYN100287', 'MYN100288', 'MYN100289', 'MYN100290', 'MYN100291', 'MYN100292', 'MYN100293', 'MYN100294', 'MYN100295', 'MYN100296', 'MYN100297', 'MYN100298', 'MYN100299', 'MYN100300', 'MYN100301', 'MYN100302', 'MYN100303', 'MYN100304', 'MYN100305', 'MYN100306', 'MYN100307', 'MYN100308', 'MYN100309', 'MYN100310', 'MYN100311', 'MYN100312', 'MYN100313', 'MYN100314', 'MYN100315', 'MYN100316', 'MYN100317', 'MYN100318', 'MYN100319', 'MYN100320', 'MYN100321', 'MYN100322', 'MYN100323', 'MYN100324', 'MYN100325', 'MYN100326', 'MYN100327', 'MYN100328', 'MYN100329', 'MYN100330', 'MYN100331', 'MYN100332', 'MYN100333', 'MYN100334', 'MYN100335', 'MYN100336', 'MYN100337', 'MYN100338', 'MYN100339', 'MYN100340', 'MYN100341', 'MYN100342', 'MYN100343', 'MYN100344', 'MYN100345', 'MYN100346', 'MYN100347', 'MYN100348', 'MYN100349', 'MYN100350', 'MYN100351', 'MYN100352', 'MYN100353', 'MYN100354', 'MYN100355', 'MYN100356', 'MYN100357', 'MYN100358', 'MYN100359', 'MYN100360', 'MYN100361', 'MYN100362', 'MYN100363', 'MYN100364', 'MYN100365', 'MYN100366', 'MYN100367', 'MYN100368', 'MYN100369', 'MYN100370', 'MYN100371', 'MYN100372', 'MYN100373', 'MYN100374', 'MYN100375', 'MYN100376', 'MYN100377', 'MYN100378', 'MYN100379', 'MYN100380', 'MYN100381', 'MYN100382', 'MYN100383', 'MYN100384', 'MYN100385', 'MYN100386', 'MYN100387', 'MYN100388', 'MYN100389', 'MYN100390', 'MYN100391', 'MYN100392', 'MYN100393', 'MYN100394', 'MYN100395', 'MYN100396', 'MYN100397', 'MYN100398', 'MYN100399', 'MYN100400', 'MYN100401', 'MYN100402', 'MYN100403', 'MYN100404', 'MYN100405', 'MYN100406', 'MYN100407', 'MYN100408', 'MYN100409', 'MYN100410', 'MYN100411', 'MYN100412', 'MYN100413', 'MYN100414', 'MYN100415', 'MYN100416', 'MYN100417', 'MYN100418', 'MYN100419', 'MYN100420', 'MYN100421', 'MYN100422', 'MYN100423', 'MYN100424', 'MYN100425', 'MYN100426', 'MYN100427', 'MYN100428', 'MYN100429', 'MYN100430', 'MYN100431', 'MYN100432', 'MYN100433', 'MYN100434', 'MYN100435', 'MYN100436', 'MYN100437', 'MYN100438', 'MYN100439', 'MYN100440', 'MYN100441', 'MYN100442', 'MYN100443', 'MYN100444', 'MYN100445', 'MYN100446', 'MYN100447', 'MYN100448', 'MYN100449', 'MYN100450', 'MYN100451', 'MYN100452', 'MYN100453', 'MYN100454', 'MYN100455', 'MYN100456', 'MYN100457', 'MYN100458', 'MYN100459', 'MYN100460', 'MYN100461', 'MYN100462', 'MYN100463', 'MYN100464', 'MYN100465', 'MYN100466', 'MYN100467', 'MYN100468', 'MYN100469', 'MYN100470', 'MYN100471', 'MYN100472', 'MYN100473', 'MYN100474', 'MYN100475', 'MYN100476', 'MYN100477', 'MYN100478', 'MYN100479', 'MYN100480', 'MYN100481', 'MYN100482', 'MYN100483', 'MYN100484', 'MYN100485', 'MYN100486', 'MYN100487', 'MYN100488', 'MYN100489', 'MYN100490', 'MYN100491', 'MYN100492', 'MYN100493', 'MYN100494', 'MYN100495', 'MYN100496', 'MYN100497', 'MYN100498', 'MYN100499', 'MYN100500', 'MYN100501', 'MYN100502', 'MYN100503', 'MYN100504', 'MYN100505', 'MYN100506', 'MYN100507', 'MYN100508', 'MYN100509', 'MYN100510', 'MYN100511', 'MYN100512', 'MYN100513', 'MYN100514', 'MYN100515', 'MYN100516', 'MYN100517', 'MYN100518', 'MYN100519', 'MYN100520', 'MYN100521', 'MYN100522', 'MYN100523', 'MYN100524', 'MYN100525', 'MYN100526', 'MYN100527', 'MYN100528', 'MYN100529', 'MYN100530', 'MYN100531', 'MYN100532', 'MYN100533', 'MYN100534', 'MYN100535', 'MYN100536', 'MYN100537', 'MYN100538', 'MYN100539', 'MYN100540', 'MYN100541', 'MYN100542', 'MYN100543', 'MYN100544', 'MYN100545', 'MYN100546', 'MYN100547', 'MYN100548', 'MYN100549', 'MYN100550', 'MYN100551', 'MYN100552', 'MYN100553', 'MYN100554', 'MYN100555', 'MYN100556', 'MYN100557', 'MYN100558', 'MYN100559', 'MYN100560', 'MYN100561', 'MYN100562', 'MYN100563', 'MYN100564', 'MYN100565', 'MYN100566', 'MYN100567', 'MYN100568', 'MYN100569', 'MYN100570', 'MYN100571', 'MYN100572', 'MYN100573', 'MYN100574', 'MYN100575', 'MYN100576', 'MYN100577', 'MYN100578', 'MYN100579', 'MYN100580', 'MYN100581', 'MYN100582', 'MYN100583', 'MYN100584', 'MYN100585', 'MYN100586', 'MYN100587', 'MYN100588', 'MYN100589', 'MYN100590', 'MYN100591', 'MYN100592', 'MYN100593', 'MYN100594', 'MYN100595', 'MYN100596', 'MYN100597', 'MYN100598', 'MYN100599', 'MYN100600', 'MYN100601', 'MYN100602', 'MYN100603', 'MYN100604', 'MYN100605', 'MYN100606', 'MYN100607', 'MYN100608', 'MYN100609', 'MYN100610', 'MYN100611', 'MYN100612', 'MYN100613', 'MYN100614', 'MYN100615', 'MYN100616', 'MYN100617', 'MYN100618', 'MYN100619', 'MYN100620', 'MYN100621', 'MYN100622', 'MYN100623', 'MYN100624', 'MYN100625', 'MYN100626', 'MYN100627', 'MYN100628', 'MYN100629', 'MYN100630', 'MYN100631', 'MYN100632', 'MYN100633', 'MYN100634', 'MYN100635', 'MYN100636', 'MYN100637', 'MYN100638', 'MYN100639', 'MYN100640', 'MYN100641', 'MYN100642', 'MYN100643', 'MYN100644', 'MYN100645', 'MYN100646', 'MYN100647', 'MYN100648', 'MYN100649', 'MYN100650', 'MYN100651', 'MYN100652', 'MYN100653', 'MYN100654', 'MYN100655', 'MYN100656', 'MYN100657', 'MYN100658', 'MYN100659', 'MYN100660', 'MYN100661', 'MYN100662', 'MYN100663', 'MYN100664', 'MYN100665', 'MYN100666', 'MYN100667', 'MYN100668', 'MYN100669', 'MYN100670', 'MYN100671', 'MYN100672', 'MYN100673', 'MYN100674', 'MYN100675', 'MYN100676', 'MYN100677', 'MYN100678', 'MYN100679', 'MYN100680', 'MYN100681', 'MYN100682', 'MYN100683', 'MYN100684', 'MYN100685', 'MYN100686', 'MYN100687', 'MYN100688', 'MYN100689', 'MYN100690', 'MYN100691', 'MYN100692', 'MYN100693', 'MYN100694', 'MYN100695', 'MYN100696', 'MYN100697', 'MYN100698', 'MYN100699', 'MYN100700', 'MYN100701', 'MYN100702', 'MYN100703', 'MYN100704', 'MYN100705', 'MYN100706', 'MYN100707', 'MYN100708', 'MYN100709', 'MYN100710', 'MYN100711', 'MYN100712', 'MYN100713', 'MYN100714', 'MYN100715', 'MYN100716', 'MYN100717', 'MYN100718', 'MYN100719', 'MYN100720', 'MYN100721', 'MYN100722', 'MYN100723', 'MYN100724', 'MYN100725', 'MYN100726', 'MYN100727', 'MYN100728', 'MYN100729', 'MYN100730', 'MYN100731', 'MYN100732', 'MYN100733', 'MYN100734', 'MYN100735', 'MYN100736', 'MYN100737', 'MYN100738', 'MYN100739', 'MYN100740', 'MYN100741', 'MYN100742', 'MYN100743', 'MYN100744', 'MYN100745', 'MYN100746', 'MYN100747', 'MYN100748', 'MYN100749', 'MYN100750', 'MYN100751', 'MYN100752', 'MYN100753', 'MYN100754', 'MYN100755', 'MYN100756', 'MYN100757', 'MYN100758', 'MYN100759', 'MYN100760', 'MYN100761', 'MYN100762', 'MYN100763', 'MYN100764', 'MYN100765', 'MYN100766', 'MYN100767', 'MYN100768', 'MYN100769', 'MYN100770', 'MYN100771', 'MYN100772', 'MYN100773', 'MYN100774', 'MYN100775', 'MYN100776', 'MYN100777', 'MYN100778', 'MYN100779', 'MYN100780', 'MYN100781', 'MYN100782', 'MYN100783', 'MYN100784', 'MYN100785', 'MYN100786', 'MYN100787', 'MYN100788', 'MYN100789', 'MYN100790', 'MYN100791', 'MYN100792', 'MYN100793', 'MYN100794', 'MYN100795', 'MYN100796', 'MYN100797', 'MYN100798', 'MYN100799', 'MYN100800', 'MYN100801', 'MYN100802', 'MYN100803', 'MYN100804', 'MYN100805', 'MYN100806', 'MYN100807', 'MYN100808', 'MYN100809', 'MYN100810', 'MYN100811', 'MYN100812', 'MYN100813', 'MYN100814', 'MYN100815', 'MYN100816', 'MYN100817', 'MYN100818', 'MYN100819', 'MYN100820', 'MYN100821', 'MYN100822', 'MYN100823', 'MYN100824', 'MYN100825', 'MYN100826', 'MYN100827', 'MYN100828', 'MYN100829', 'MYN100830', 'MYN100831', 'MYN100832', 'MYN100833', 'MYN100834', 'MYN100835', 'MYN100836', 'MYN100837', 'MYN100838', 'MYN100839', 'MYN100840', 'MYN100841', 'MYN100842', 'MYN100843', 'MYN100844', 'MYN100845', 'MYN100846', 'MYN100847', 'MYN100848', 'MYN100849', 'MYN100850', 'MYN100851', 'MYN100852', 'MYN100853', 'MYN100854', 'MYN100855', 'MYN100856', 'MYN100857', 'MYN100858', 'MYN100859', 'MYN100860', 'MYN100861', 'MYN100862', 'MYN100863', 'MYN100864', 'MYN100865', 'MYN100866', 'MYN100867', 'MYN100868', 'MYN100869', 'MYN100870', 'MYN100871', 'MYN100872', 'MYN100873', 'MYN100874', 'MYN100875', 'MYN100876', 'MYN100877', 'MYN100878', 'MYN100879', 'MYN100880', 'MYN100881', 'MYN100882', 'MYN100883', 'MYN100884', 'MYN100885', 'MYN100886', 'MYN100887', 'MYN100888', 'MYN100889', 'MYN100890', 'MYN100891', 'MYN100892', 'MYN100893', 'MYN100894', 'MYN100895', 'MYN100896', 'MYN100897', 'MYN100898', 'MYN100899', 'MYN100900', 'MYN100901', 'MYN100902', 'MYN100903', 'MYN100904', 'MYN100905', 'MYN100906', 'MYN100907', 'MYN100908', 'MYN100909', 'MYN100910', 'MYN100911', 'MYN100912', 'MYN100913', 'MYN100914', 'MYN100915', 'MYN100916', 'MYN100917', 'MYN100918', 'MYN100919', 'MYN100920', 'MYN100921', 'MYN100922', 'MYN100923', 'MYN100924', 'MYN100925', 'MYN100926', 'MYN100927', 'MYN100928', 'MYN100929', 'MYN100930', 'MYN100931', 'MYN100932', 'MYN100933', 'MYN100934', 'MYN100935', 'MYN100936', 'MYN100937', 'MYN100938', 'MYN100939', 'MYN100940', 'MYN100941', 'MYN100942', 'MYN100943', 'MYN100944', 'MYN100945', 'MYN100946', 'MYN100947', 'MYN100948', 'MYN100949', 'MYN100950', 'MYN100951', 'MYN100952', 'MYN100953', 'MYN100954', 'MYN100955', 'MYN100956', 'MYN100957', 'MYN100958', 'MYN100959', 'MYN100960', 'MYN100961', 'MYN100962', 'MYN100963', 'MYN100964', 'MYN100965', 'MYN100966', 'MYN100967', 'MYN100968', 'MYN100969', 'MYN100970', 'MYN100971', 'MYN100972', 'MYN100973', 'MYN100974', 'MYN100975', 'MYN100976', 'MYN100977', 'MYN100978', 'MYN100979', 'MYN100980', 'MYN100981', 'MYN100982', 'MYN100983', 'MYN100984', 'MYN100985', 'MYN100986', 'MYN100987', 'MYN100988', 'MYN100989', 'MYN100990', 'MYN100991', 'MYN100992', 'MYN100993', 'MYN100994', 'MYN100995', 'MYN100996', 'MYN100997', 'MYN100998', 'MYN100999', 'MYN101000', 'MYN101001', 'MYN101002', 'MYN101003', 'MYN101004', 'MYN101005', 'MYN101006', 'MYN101007', 'MYN101008', 'MYN101009', 'MYN101010', 'MYN101011', 'MYN101012', 'MYN101013', 'MYN101014', 'MYN101015', 'MYN101016', 'MYN101017', 'MYN101018', 'MYN101019', 'MYN101020', 'MYN101021', 'MYN101022', 'MYN101023', 'MYN101024', 'MYN101025', 'MYN101026', 'MYN101027', 'MYN101028', 'MYN101029', 'MYN101030', 'MYN101031', 'MYN101032', 'MYN101033', 'MYN101034', 'MYN101035', 'MYN101036', 'MYN101037', 'MYN101038', 'MYN101039', 'MYN101040', 'MYN101041', 'MYN101042', 'MYN101043', 'MYN101044', 'MYN101045', 'MYN101046', 'MYN101047', 'MYN101048', 'MYN101049', 'MYN101050', 'MYN101051', 'MYN101052', 'MYN101053', 'MYN101054', 'MYN101055', 'MYN101056', 'MYN101057', 'MYN101058', 'MYN101059', 'MYN101060', 'MYN101061', 'MYN101062', 'MYN101063', 'MYN101064', 'MYN101065', 'MYN101066', 'MYN101067', 'MYN101068', 'MYN101069', 'MYN101070', 'MYN101071', 'MYN101072', 'MYN101073', 'MYN101074', 'MYN101075', 'MYN101076', 'MYN101077', 'MYN101078', 'MYN101079', 'MYN101080', 'MYN101081', 'MYN101082', 'MYN101083', 'MYN101084', 'MYN101085', 'MYN101086', 'MYN101087', 'MYN101088', 'MYN101089', 'MYN101090', 'MYN101091', 'MYN101092', 'MYN101093', 'MYN101094', 'MYN101095', 'MYN101096', 'MYN101097', 'MYN101098', 'MYN101099', 'MYN101100', 'MYN101101', 'MYN101102', 'MYN101103', 'MYN101104', 'MYN101105', 'MYN101106', 'MYN101107', 'MYN101108', 'MYN101109', 'MYN101110', 'MYN101111', 'MYN101112', 'MYN101113', 'MYN101114', 'MYN101115', 'MYN101116', 'MYN101117', 'MYN101118', 'MYN101119', 'MYN101120', 'MYN101121', 'MYN101122', 'MYN101123', 'MYN101124', 'MYN101125', 'MYN101126', 'MYN101127', 'MYN101128', 'MYN101129', 'MYN101130', 'MYN101131', 'MYN101132', 'MYN101133', 'MYN101134', 'MYN101135', 'MYN101136', 'MYN101137', 'MYN101138', 'MYN101139', 'MYN101140', 'MYN101141', 'MYN101142', 'MYN101143', 'MYN101144', 'MYN101145', 'MYN101146', 'MYN101147', 'MYN101148', 'MYN101149', 'MYN101150', 'MYN101151', 'MYN101152', 'MYN101153', 'MYN101154', 'MYN101155', 'MYN101156', 'MYN101157', 'MYN101158', 'MYN101159', 'MYN101160', 'MYN101161', 'MYN101162', 'MYN101163', 'MYN101164', 'MYN101165', 'MYN101166', 'MYN101167', 'MYN101168', 'MYN101169', 'MYN101170', 'MYN101171', 'MYN101172', 'MYN101173', 'MYN101174', 'MYN101175', 'MYN101176', 'MYN101177', 'MYN101178', 'MYN101179', 'MYN101180', 'MYN101181', 'MYN101182', 'MYN101183', 'MYN101184', 'MYN101185', 'MYN101186', 'MYN101187', 'MYN101188', 'MYN101189', 'MYN101190', 'MYN101191', 'MYN101192', 'MYN101193', 'MYN101194', 'MYN101195', 'MYN101196', 'MYN101197', 'MYN101198', 'MYN101199', 'MYN101200', 'MYN101201', 'MYN101202', 'MYN101203', 'MYN101204', 'MYN101205', 'MYN101206', 'MYN101207', 'MYN101208', 'MYN101209', 'MYN101210', 'MYN101211', 'MYN101212', 'MYN101213', 'MYN101214', 'MYN101215', 'MYN101216', 'MYN101217', 'MYN101218', 'MYN101219', 'MYN101220', 'MYN101221', 'MYN101222', 'MYN101223', 'MYN101224', 'MYN101225', 'MYN101226', 'MYN101227', 'MYN101228', 'MYN101229', 'MYN101230', 'MYN101231', 'MYN101232', 'MYN101233', 'MYN101234', 'MYN101235', 'MYN101236', 'MYN101237', 'MYN101238', 'MYN101239', 'MYN101240', 'MYN101241', 'MYN101242', 'MYN101243', 'MYN101244', 'MYN101245', 'MYN101246', 'MYN101247', 'MYN101248', 'MYN101249', 'MYN101250', 'MYN101251', 'MYN101252', 'MYN101253', 'MYN101254', 'MYN101255', 'MYN101256', 'MYN101257', 'MYN101258', 'MYN101259', 'MYN101260', 'MYN101261', 'MYN101262', 'MYN101263', 'MYN101264', 'MYN101265', 'MYN101266', 'MYN101267', 'MYN101268', 'MYN101269', 'MYN101270', 'MYN101271', 'MYN101272', 'MYN101273', 'MYN101274', 'MYN101275', 'MYN101276', 'MYN101277', 'MYN101278', 'MYN101279', 'MYN101280', 'MYN101281', 'MYN101282', 'MYN101283', 'MYN101284', 'MYN101285', 'MYN101286', 'MYN101287', 'MYN101288', 'MYN101289', 'MYN101290', 'MYN101291', 'MYN101292', 'MYN101293', 'MYN101294', 'MYN101295', 'MYN101296', 'MYN101297', 'MYN101298', 'MYN101299', 'MYN101300', 'MYN101301', 'MYN101302', 'MYN101303', 'MYN101304', 'MYN101305', 'MYN101306', 'MYN101307', 'MYN101308', 'MYN101309', 'MYN101310', 'MYN101311', 'MYN101312', 'MYN101313', 'MYN101314', 'MYN101315', 'MYN101316', 'MYN101317', 'MYN101318', 'MYN101319', 'MYN101320', 'MYN101321', 'MYN101322', 'MYN101323', 'MYN101324', 'MYN101325', 'MYN101326', 'MYN101327', 'MYN101328', 'MYN101329', 'MYN101330', 'MYN101331', 'MYN101332', 'MYN101333', 'MYN101334', 'MYN101335', 'MYN101336', 'MYN101337', 'MYN101338', 'MYN101339', 'MYN101340', 'MYN101341', 'MYN101342', 'MYN101343', 'MYN101344', 'MYN101345', 'MYN101346', 'MYN101347', 'MYN101348', 'MYN101349', 'MYN101350', 'MYN101351', 'MYN101352', 'MYN101353', 'MYN101354', 'MYN101355', 'MYN101356', 'MYN101357', 'MYN101358', 'MYN101359', 'MYN101360', 'MYN101361', 'MYN101362', 'MYN101363', 'MYN101364', 'MYN101365', 'MYN101366', 'MYN101367', 'MYN101368', 'MYN101369', 'MYN101370', 'MYN101371', 'MYN101372', 'MYN101373', 'MYN101374', 'MYN101375', 'MYN101376', 'MYN101377', 'MYN101378', 'MYN101379', 'MYN101380', 'MYN101381', 'MYN101382', 'MYN101383', 'MYN101384', 'MYN101385', 'MYN101386', 'MYN101387', 'MYN101388', 'MYN101389', 'MYN101390', 'MYN101391', 'MYN101392', 'MYN101393', 'MYN101394', 'MYN101395', 'MYN101396', 'MYN101397', 'MYN101398', 'MYN101399', 'MYN101400', 'MYN101401', 'MYN101402', 'MYN101403', 'MYN101404', 'MYN101405', 'MYN101406', 'MYN101407', 'MYN101408', 'MYN101409', 'MYN101410', 'MYN101411', 'MYN101412', 'MYN101413', 'MYN101414', 'MYN101415', 'MYN101416', 'MYN101417', 'MYN101418', 'MYN101419', 'MYN101420', 'MYN101421', 'MYN101422', 'MYN101423', 'MYN101424', 'MYN101425', 'MYN101426', 'MYN101427', 'MYN101428', 'MYN101429', 'MYN101430', 'MYN101431', 'MYN101432', 'MYN101433', 'MYN101434', 'MYN101435', 'MYN101436', 'MYN101437', 'MYN101438', 'MYN101439', 'MYN101440', 'MYN101441', 'MYN101442', 'MYN101443', 'MYN101444', 'MYN101445', 'MYN101446', 'MYN101447', 'MYN101448', 'MYN101449', 'MYN101450', 'MYN101451', 'MYN101452', 'MYN101453', 'MYN101454', 'MYN101455', 'MYN101456', 'MYN101457', 'MYN101458', 'MYN101459', 'MYN101460', 'MYN101461', 'MYN101462', 'MYN101463', 'MYN101464', 'MYN101465', 'MYN101466', 'MYN101467', 'MYN101468', 'MYN101469', 'MYN101470', 'MYN101471', 'MYN101472', 'MYN101473', 'MYN101474', 'MYN101475', 'MYN101476', 'MYN101477', 'MYN101478', 'MYN101479', 'MYN101480', 'MYN101481', 'MYN101482', 'MYN101483', 'MYN101484', 'MYN101485', 'MYN101486', 'MYN101487', 'MYN101488', 'MYN101489', 'MYN101490', 'MYN101491', 'MYN101492', 'MYN101493', 'MYN101494', 'MYN101495', 'MYN101496', 'MYN101497', 'MYN101498', 'MYN101499', 'MYN101500', 'MYN101501', 'MYN101502', 'MYN101503', 'MYN101504', 'MYN101505', 'MYN101506', 'MYN101507', 'MYN101508', 'MYN101509', 'MYN101510', 'MYN101511', 'MYN101512', 'MYN101513', 'MYN101514', 'MYN101515', 'MYN101516', 'MYN101517', 'MYN101518', 'MYN101519', 'MYN101520', 'MYN101521', 'MYN101522', 'MYN101523', 'MYN101524', 'MYN101525', 'MYN101526', 'MYN101527', 'MYN101528', 'MYN101529', 'MYN101530', 'MYN101531', 'MYN101532', 'MYN101533', 'MYN101534', 'MYN101535', 'MYN101536', 'MYN101

In [11]:
pd.crosstab(df['category'], df['size'])

size            10   11    6   7    8    9    L    M    S   XL   XS  XXL
category
Beauty           0    0    0   0    0    0  204  193  173  196  186  164
Footwear       104  104  113  99  113  101    0    0    0    0    0    0
Home & Living    0    0    0   0    0    0   79   85   81   75   65   88
Kids            28   29   33  26   20   32  147  163  159  169  148  152
Men             50   28   59  50   53   52  303  354  306  320  358  281
Women           55   55   61  45   53   49  391  328  348  357  374  341

In [13]:
# remove white space from object 
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

In [14]:
for col in df.select_dtypes(include='object').columns:
    if df[col].str.startswith(' ', na=False).any() or df[col].str.endswith(' ', na=False).any():
        print(f"Whitespace still exists in: {col}")

In [22]:
df.to_sql(name="clean_dataset",
          con=engine , 
          if_exists="replace" , 
          index=False,
          chunksize=500)
print("clean dataset save in mysql")

clean dataset save in mysql

In [23]:
df_verify = pd.read_sql("SELECT * FROM clean_dataset LIMIT 5", engine)
display(df_verify)

,order_id,order_date,order_month,order_quarter,order_year,customer_id,gender,age,city,state,...,mrp,discount_percent,selling_price,quantity,total_amount,payment_mode,order_channel,order_status,delivery_days,rating
0,MYN100001,2023-03-03,March,Q1,2023,CUST00139,Female,27,Delhi,Delhi,...,5729.0,50,2864.5,1,2864.5,UPI,Website,Delivered,3,5.0
1,MYN100002,2024-03-13,March,Q1,2024,CUST00298,Female,40,Guwahati,Assam,...,2129.0,0,2129.0,1,2129.0,Debit Card,Mobile App,Delivered,9,5.0
2,MYN100003,2025-05-13,May,Q2,2025,CUST01162,Female,39,Kolkata,West Bengal,...,5699.0,10,5129.1,1,5129.1,Credit Card,Mobile App,Delivered,8,3.0
3,MYN100004,2023-02-13,February,Q1,2023,CUST02043,Male,48,Jaipur,Rajasthan,...,2169.0,30,1518.3,1,1518.3,UPI,Mobile App,Cancelled,6,4.0
4,MYN100005,2023-07-14,July,Q3,2023,CUST00020,Male,52,Surat,Gujarat,...,1729.0,0,1729.0,1,1729.0,Cash on Delivery,Website,Delivered,8,4.0

In [24]:
original_count = pd.read_sql("SELECT COUNT(*) AS cnt FROM clean_dataset", engine)
print(f"✓ Rows in MySQL  : {original_count['cnt'][0]}")
print(f"✓ Rows in df     : {len(df)}")
print(f"✓ Match          : {original_count['cnt'][0] == len(df)}")

✓ Rows in MySQL  : 8000
✓ Rows in df     : 8000
✓ Match          : True

In [25]:
df.to_csv('clean_dataset.csv',index=False)