In [1]:
import pandas as pd
df = pd.read_csv("website_analysis.csv" ,skiprows=1)
display(df.head(5))

,Session primary channel group (Default channel group),Date + hour (YYYYMMDDHH),Users,Sessions,Engaged sessions,Average engagement time per session,Engaged sessions per user,Events per session,Engagement rate,Event count
0,Direct,2024041623,237,300,144,47.526667,0.607595,4.673333,0.480000,1402
1,Organic Social,2024041719,208,267,132,32.097378,0.634615,4.295880,0.494382,1147
2,Direct,2024041723,188,233,115,39.939914,0.611702,4.587983,0.493562,1069
3,Organic Social,2024041718,187,256,125,32.160156,0.668449,4.078125,0.488281,1044
4,Organic Social,2024041720,175,221,112,46.918552,0.640000,4.529412,0.506787,1001

In [2]:
df = df.rename(columns={
    "Session primary channel group (Default channel group)" : "chenal_group",
    "Date + hour (YYYYMMDDHH)" : "date_hour",
    "Users" : "user",
    "Sessions" : "session",
    "Engaged sessions" : "engaged_session",
    "Average engagement time per session" : "avg_eng_time_per_session" ,
    "Engaged sessions per user" : "engaged_session_per_user",
    "Events per session" : "event_per_session",
    "Engagement rate" : "engagement_rate" , 
    "Event count" : "event_count"
})
df

,chenal_group,date_hour,user,session,engaged_session,avg_eng_time_per_session,engaged_session_per_user,event_per_session,engagement_rate,event_count
0,Direct,2024041623,237,300,144,47.526667,0.607595,4.673333,0.480000,1402
1,Organic Social,2024041719,208,267,132,32.097378,0.634615,4.295880,0.494382,1147
2,Direct,2024041723,188,233,115,39.939914,0.611702,4.587983,0.493562,1069
3,Organic Social,2024041718,187,256,125,32.160156,0.668449,4.078125,0.488281,1044
4,Organic Social,2024041720,175,221,112,46.918552,0.640000,4.529412,0.506787,1001
...,...,...,...,...,...,...,...,...,...,...
3177,Unassigned,2024042806,0,1,0,0.000000,0.000000,2.000000,0.000000,2
3178,Unassigned,2024043005,0,1,0,0.000000,0.000000,2.000000,0.000000,2
3179,Unassigned,2024043006,0,1,0,0.000000,0.000000,2.000000,0.000000,2
3180,Unassigned,2024050105,0,1,0,0.000000,0.000000,2.000000,0.000000,2
3181,Unassigned,2024050307,0,1,0,0.000000,0.000000,2.000000,0.000000,2

In [19]:
print(df.info())
print("-"*20)
print(f"null check : \n{df.isnull().sum()}")
print("-"*20)
print(f"duplicate check : {df.duplicated().sum()}")
print("-"*20)
print(f"data shape :{df.shape}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   chenal_group              3182 non-null   object
 1   user                      3182 non-null   int64
 2   session                   3182 non-null   int64
 3   engaged_session           3182 non-null   int64
 4   avg_eng_time_per_session  3182 non-null   float64
 5   engaged_session_per_user  3182 non-null   float64
 6   event_per_session         3182 non-null   float64
 7   engagement_rate           3182 non-null   float64
 8   event_count               3182 non-null   int64
 9   date                      3182 non-null   datetime64[ns]
 10  hour                      3182 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(5), object(1)
memory usage: 273.6+ KB
None
--------------------
null check :
chenal_group                0
user                        0
session                     0
engaged_session             0
avg_eng_time_per_session    0
engaged_session_per_user    0
event_per_session           0
engagement_rate             0
event_count                 0
date                        0
hour                        0
dtype: int64
--------------------
duplicate check : 0
--------------------
data shape :(3182, 11)

In [6]:
# Convert column to string first
df['date_hour'] = df['date_hour'].astype(str)

# Extract Date part (first 8 digits)
df['date'] = pd.to_datetime(
    df['date_hour'].str[:8],
    format='%Y%m%d'
)

# Extract Hour part (last 2 digits)
df['hour'] = df['date_hour'].str[8:10].astype(int)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   chenal_group              3182 non-null   object
 1   date_hour                 3182 non-null   object
 2   user                      3182 non-null   int64
 3   session                   3182 non-null   int64
 4   engaged_session           3182 non-null   int64
 5   avg_eng_time_per_session  3182 non-null   float64
 6   engaged_session_per_user  3182 non-null   float64
 7   event_per_session         3182 non-null   float64
 8   engagement_rate           3182 non-null   float64
 9   event_count               3182 non-null   int64
 10  date                      3182 non-null   datetime64[ns]
 11  hour                      3182 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(5), object(2)
memory usage: 298.4+ KB

In [18]:
for i in df.select_dtypes(include="object"):
    print(f"{i} : \n{df[i].unique()}")

chenal_group :
['Direct' 'Organic Social' 'Organic Search' 'Referral' 'Unassigned'
 'Organic Video' 'Email']

In [25]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

In [26]:
df.to_csv('clean_data.csv' , index=False)